services:
  - type: web
    name: data-analysis-app
    runtime: node
    region: frankfurt
    rootDir: data-analysis-app
    buildCommand: cd client && npm ci --include=dev && npm run build && cd ../server && npm ci
    startCommand: cd server && node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 7d
      - key: ADMIN_MASTER_KEY
        sync: false
